# Generated by Django 3.2.9 on 2021-11-14 15:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('affix', models.CharField(blank=True, max_length=5, null=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=8)),
                ('religion', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='WorkProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hiring_date', models.DateField()),
                ('current_position', models.CharField(max_length=250)),
                ('division', models.CharField(blank=True, max_length=250, null=True)),
                ('group', models.CharField(blank=True, max_length=250, null=True)),
                ('department', models.CharField(blank=True, max_length=250, null=True)),
                ('team', models.CharField(blank=True, max_length=250, null=True)),
                ('subteam', models.CharField(blank=True, max_length=250, null=True)),
                ('unit', models.CharField(blank=True, max_length=250, null=True)),
                ('subunit', models.CharField(blank=True, max_length=250, null=True)),
                ('section', models.CharField(blank=True, max_length=250, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.personaldata')),
            ],
            options={
                'verbose_name_plural': 'Work Profile',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports_to_id', models.PositiveIntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.personaldata')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin', models.CharField(max_length=250)),
                ('tax_exemption_status', models.CharField(max_length=250)),
                ('hmdf', models.CharField(blank=True, max_length=250, null=True)),
                ('philhealth', models.CharField(blank=True, max_length=250, null=True)),
                ('sss', models.CharField(blank=True, max_length=250, null=True)),
                ('gsis', models.CharField(blank=True, max_length=250, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.personaldata')),
            ],
            options={
                'verbose_name_plural': 'Government Related',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('affix', models.CharField(blank=True, max_length=5, null=True)),
                ('birth_date', models.DateField()),
                ('relationship', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Sibling', 'Sibling'), ('Wife', 'Wife'), ('Child', 'Child')], max_length=7)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', models.CharField(max_length=25)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.personaldata')),
            ],
            options={
                'verbose_name_plural': 'Family Members',
            },
        ),
        migrations.CreateModel(
            name='EmployeeMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=250)),
                ('old_position', models.CharField(max_length=250)),
                ('new_position', models.CharField(max_length=250)),
                ('old_division', models.CharField(blank=True, max_length=250, null=True)),
                ('new_division', models.CharField(blank=True, max_length=250, null=True)),
                ('old_group', models.CharField(blank=True, max_length=250, null=True)),
                ('new_group', models.CharField(blank=True, max_length=250, null=True)),
                ('old_department', models.CharField(blank=True, max_length=250, null=True)),
                ('new_department', models.CharField(blank=True, max_length=250, null=True)),
                ('old_team', models.CharField(blank=True, max_length=250, null=True)),
                ('new_team', models.CharField(blank=True, max_length=250, null=True)),
                ('old_subteam', models.CharField(blank=True, max_length=250, null=True)),
                ('new_subteam', models.CharField(blank=True, max_length=250, null=True)),
                ('old_unit', models.CharField(blank=True, max_length=250, null=True)),
                ('new_unit', models.CharField(blank=True, max_length=250, null=True)),
                ('old_subunit', models.CharField(blank=True, max_length=250, null=True)),
                ('new_subunit', models.CharField(blank=True, max_length=250, null=True)),
                ('old_section', models.CharField(blank=True, max_length=250, null=True)),
                ('new_section', models.CharField(blank=True, max_length=250, null=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.personaldata')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=250)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('major', models.CharField(blank=True, max_length=250, null=True)),
                ('minor', models.CharField(blank=True, max_length=250, null=True)),
                ('degree', models.CharField(blank=True, max_length=250, null=True)),
                ('award', models.CharField(blank=True, max_length=250, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.personaldata')),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense', models.CharField(max_length=250)),
                ('penalty', models.CharField(blank=True, max_length=250, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.personaldata')),
            ],
            options={
                'verbose_name_plural': 'Disciplinary Action',
            },
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TR', 'Temporary Residence'), ('PR', 'Permanent Residence'), ('PA', 'Provincial Address'), ('OL', 'Office Location'), ('EC', 'Emergency Contact')], max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('contact_person', models.CharField(blank=True, max_length=25, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.personaldata')),
            ],
            options={
                'verbose_name_plural': 'Contact Information',
            },
        ),
    ]
