# Generated by Django 3.2.9 on 2021-12-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='present_city',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldata',
            name='present_province',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
