# Generated by Django 3.2.9 on 2021-11-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='email',
            field=models.EmailField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldata',
            name='phone_number',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
    ]
